### PR TITLE
Changed instances of "Address Book" to "Truth Table"

### PR DESCRIPTION
**Pull request by ling-ui**

### CODE REVIEW

**Comment by mjgui** [comment]
Blocked by #55 , #75 

Will need to fix a lot of merge conflicts... so probably better to merge it before any other feature branches

**Comment by mjgui** [comment]
As per discussion, will shift this to milestone v1.4 as it's only internal refactoring

**Comment by Devanshshah1309** [comment]
@ling-ui Is it possible to resolve conflicts and get this merged soon?

**Comment by Devanshshah1309** [comment]
Creating a new PR to fix this (as discussed internally)

**Pull request closed without merging**
