### PR TITLE
Fix exception and help messages

### LINKED ISSUE #139: [PE-D][Tester C] Exception error can be seen in user interface when invalid index is given
When an invalid index is given in a command, such as the one given below, the exception error message shows up in the user interface.

This is bug is very minor and purely cosmetic, but it might be a bit confusing to users.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: normkoh/ped#3

### LINKED ISSUE #180: Help message for each command not meaningful.
The help message displayed for each command only displays the usage of each command, but not what the command does.

Suggestion: Add what the command does on top of the usage message.

image

### LINKED ISSUE #193: Inconsistent help messages
Variable names in `Command` classes are different even with the same type.

For instance,  the `add member` command where the help message says `<targetPersonIndex>` but our UG says `PersonIndex`

### PR DESCRIPTION
**Pull request by Devanshshah1309**
The error message sounds very generic (since it doesn't even include the command itself) but I'm not sure if anything can be done about it coz we don't have access to `commandName` inside that block.

Fixes #139
Fixes #180 
Fixed #193

### CODE REVIEW

**Comment by marcuspang** [comment]
@Devanshshah1309 you can make use of `TypeConversionException` to print a better error message for converter errors (like the one in the message)

See https://picocli.info/#_handling_invalid_input

So when `TruthTableParser` catches this exception, you can simply throw the message.

**Review by marcuspang — CHANGES_REQUESTED** [review]
@Devanshshah1309 you can make use of `TypeConversionException` to print a better error message for converter errors (like the one in the message)

See https://picocli.info/#_handling_invalid_input

So when `TruthTableParser` catches this exception, you can simply throw the message.

But for the `PicocliException`, we can leave it as it is

**Comment by Devanshshah1309** [comment]
@marcuspang even after I add the try-catch block for `CommandLine.TypeConversionException`, for some reason the `add member 0` command falls to the `CommandLine.PicocliException` block. Any idea why?
The code looks something like this:
```
 } catch (CommandLine.TypeConversionException e) {
            throw new ParseException(String.format("Type conversion error: ", e.getMessage()));
 } catch (CommandLine.PicocliException e) {
            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
                   MESSAGE_INVALID_COMMAND_FORMAT_PARSE_EXCEPTION));
 }
```

**Comment by Devanshshah1309** [comment]
Btw I'm deleting all the unused `MESSAGE_USAGE` variables (any reason why its only used for the `list tasks` command?)

**Comment by marcuspang** [comment]
> @marcuspang even after I add the try-catch block for `CommandLine.TypeConversionException`, for some reason the `add member 0` command falls to the `CommandLine.PicocliException` block. Any idea why? The code looks something like this:
> 
> ```
>  } catch (CommandLine.TypeConversionException e) {
>             throw new ParseException("Type conversion error: " + e.getMessage());
>  } catch (CommandLine.PicocliException e) {
>             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
>                    MESSAGE_INVALID_COMMAND_FORMAT_PARSE_EXCEPTION));
>  }
> ```

image

The reason is because `.parseArgs()` throws a `ParameterException` and `TypeConversionException` is not a subclass of `ParameterException`

**Review by marcuspang — APPROVED** [review]
LGTM, tidied up the help messages by using the `FULL_COMMAND` constants

**Pull request merged**
